### ISSUE TITLE
[Question] Locating exact cords of the player

### ISSUE THREAD

**Issue by OstojaOfficial** [nerdsinspace/nocom-explanation#11]
I have a question. If nocom gets a response that a specific chunk is loaded, shouldn't it also mean that chanks surrounding it could also be loaded due to players render distance my guess is that you do scan around that area for all loaded chunks and then get the loaded chunk in the middle which should be the chunk where player is in right now, also spawn chunks should be always loaded so I don't know how nocom is able to track players inside the spawn area. My question is how is nocom able to find exact cords of the player inside the loaded chunks? Because from what I understand, it only checks if chunk is loaded or not, that information doesn't say where player is located inside the chunk.

**Comment by thelampgod** [comment]
It doesnt

**Comment by 0-x-2-2** [comment]
The algorithm will learn and resolve the players exact position over time but that was never intended but it does.

**Comment by IronException** [comment]
on 2b spawn chunks arent always loaded

**Comment by 0-x-2-2** [comment]
> My question is how is nocom able to find exact cords of the player inside the loaded chunks

Players load more then one chunk so as long as multiple players are not in the same chunk its possible to even figure out the location of other players in the render distance.

**Comment by OstojaOfficial** [comment]
> The algorithm will learn and resolve the players exact position over time but that was never intended but it does.

Will the tracking algorithm and maybe other algorithms that were used be explained in the future how they work?

**Comment by leijurv** [comment]
It cannot locate a player to within sub-chunk accuracy unless they are moving. If someone is moving at a consistent speed, it can realize the exact instant that they cross the boundary from one chunk to another. As it notices those events, the particles will converge on the player's location and speed at sub-chunk accuracy. However this is impossible if the player is stationary.
