### ISSUE TITLE
[Question] How are particles actually being filtered?

### ISSUE THREAD

**Issue by Trey-arch** [nerdsinspace/nocom-explanation#19]
I don't quite understand how you efficiently look for differences between other particles to converge on the player. I thought of something, but I don't think it'd work. First, you get a hit. Second, you check 4 chunks cardinally adjacent to the original chunk, this should allow you to get a general idea of where the hit occurred in the render distance. Then, you generate your particles and wait. You then, informed by the render distance measurement, click all the chunks in the player's render distance before they moved. You then compare this to where the hits are in the square and then do this for each particle. I think I don't understand how anything actually works and this just feels wrong though so I've been wondering how a program can do this in an orderly fashion.

Thanks.

**Comment by leijurv** [comment]
The whole "looking for differences" thing is entirely separate, that only applies to the base downloader not the tracker.

That thing you describe was my initial prototype, fit showed some clips of it, where it just prints out "gridding" then a hit. It was a 5x5 grid of 9-chunk-spaced checks. It worked fine but it was super inefficient.

The way it actually worked was natural selection of particles down to just the ones that were accurate. Ones that are close to a hit or far from a miss are more likely to be kept, ones that are close to a miss or far from a hit are more likely to be killed. Very quickly they match the player's actual position and speed, allowing us to keep up with them easily, if they are moving with a consistent speed and direction.
