### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by bloodskin** [nerdsinspace/nocom-explanation#22]
would love to see more render videos of some nice bases. obviously would have to be ones that have already been griefed, but it would be fun to see the before and after of some of the larger builds. would be a good way to monetize the data you have via youtube. just an idea.

**Comment by rebane2001** [comment]
https://www.youtube.com/watch?v=q97iUlu9DQc&list=PLOxa3ecQg7Kitnn1qpYXOR3H_qR0ogiYO
