### ISSUE TITLE
What was headless client written in? I've seen other headless clients being written in different languages, so I'm curious.

### ISSUE THREAD

**Issue by Bran3** [nerdsinspace/nocom-explanation#23]

**Comment by rebane2001** [comment]
The programming language used for the headless client was "Java" (not to be confused with JavaScript or C# programming languages).

**Comment by overlisted** [comment]
Probably Java

**Comment by Gaming32** [comment]
Minecraft is written in Java, and the article said that this headless client is more of a mod for a headless *mode*. So it's probably Java. (unless it's written with the JNI, which I doubt)
