### ISSUE TITLE
comdar 2.0

### ISSUE THREAD

**Issue by RandomTNT** [nerdsinspace/nocom-explanation#26]
apparently, if player is in queue, queue loads the chunk that the player logged off, so why dont we just track that shit also

**Comment by Bran3** [comment]
Who said it isn't tracked?
It's just that it probably isn't flagged as person in queue.
I'm sure system picked up on the loaded chunks...
Also thinking about it, this may be the reason why some players expirienced chunks being loaded when there's noone around them. (I think I recall hearing that on the podcast as one of the abnormalities)
No way to know for sure, unless nerds confirm.

**Comment by RandomTNT** [comment]
@Bran3 how come it flag the person being there

**Comment by RandomTNT** [comment]
The chunks are loaded by server, so

**Comment by 0-x-2-2** [comment]
no
