### ISSUE TITLE
No documentation for the SQL files

### ISSUE THREAD

**Issue by AffectedArc07** [nerdsinspace/nocom-explanation#27]
What language are they in? My first guess would be Postgres as thats what the rest of the suite is in, but not 100%

EDIT - Also a schema (if not already provided) would be neat.

**Comment by leijurv** [comment]
https://github.com/nerdsinspace/nocomment-master/blob/master/schema.sql

**Comment by leijurv** [comment]
Added link https://github.com/nerdsinspace/nocom-explanation/commit/be14d2b0bfc614887e10cf5484725d81e52c5514

**Comment by AffectedArc07** [comment]
> Added link https://github.com/nerdsinspace/nocom-explanation/commit/be14d2b0bfc614887e10cf5484725d81e52c5514

Cheers for that. DB is postgres then?

**Comment by leijurv** [comment]
Yeah you can see it at the top of each .sql dump, Postgres 12 specifically
